channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>=3
  - pip:
    - setuptools
    - requests
    - fuzzywuzzy
    - python-Levenshtein
    - sphinx
    - myst-parser
    - myst-nb
